import { describe, expect, test, beforeAll, afterAll } from "bun:test";
import { join } from "node:path";
import { rm, readdir } from "node:fs/promises";
import { parse as parseYaml } from "yaml";

const CLI_PATH = join(import.meta.dir, "../src/cli.ts");
const VALID_FIXTURES = join(import.meta.dir, "fixtures/valid");
const INVALID_FIXTURES = join(import.meta.dir, "fixtures/invalid");
const OUTPUT_DIR = join(import.meta.dir, "output");

async function runCli(args: string[]): Promise<{ stdout: string; stderr: string; exitCode: number }> {
  const proc = Bun.spawn(["bun", "run", CLI_PATH, ...args], {
    stdout: "pipe",
    stderr: "pipe",
  });

  const stdout = await new Response(proc.stdout).text();
  const stderr = await new Response(proc.stderr).text();
  const exitCode = await proc.exited;

  return { stdout, stderr, exitCode };
}

describe("CLI integration", () => {
  afterAll(async () => {
    await rm(OUTPUT_DIR, { recursive: true, force: true });
  });

  test("generates workflows from valid fixtures", async () => {
    const { stdout, exitCode } = await runCli([VALID_FIXTURES, OUTPUT_DIR]);

    expect(exitCode).toBe(0);
    expect(stdout).toContain("Generated");

    const files = await readdir(OUTPUT_DIR);
    expect(files).toContain("taskmaster-code-review.yml");
    expect(files).toContain("taskmaster-lint-check.yml");
    expect(files).toContain("taskmaster-dispatcher.yml");
  });

  test("generated workflow YAML is valid", async () => {
    const content = await Bun.file(join(OUTPUT_DIR, "taskmaster-code-review.yml")).text();

    // Should have auto-generated comment
    expect(content).toContain("Auto-generated by claude-taskmaster");

    // Should parse as valid YAML
    const parsed = parseYaml(content);
    expect(parsed.name).toBe("taskmaster-code-review");
    expect(parsed.on).toEqual({ workflow_call: {} });
    expect(parsed.jobs.task["runs-on"]).toBe("ubuntu-latest");

    // System prompt should be passed via --append-system-prompt in claude_args
    const actionStep = parsed.jobs.task.steps.find(
      (s: any) => s.uses === "anthropics/claude-code-action@v1"
    );
    expect(actionStep.with.prompt).toBe("Review the code changes in this PR. Focus on bugs, security issues, and code quality.");
    expect(actionStep.with.claude_args).toContain("--append-system-prompt");
    expect(actionStep.with.claude_args).toContain("helpful code review assistant");
  });

  test("generated dispatcher is valid", async () => {
    const content = await Bun.file(join(OUTPUT_DIR, "taskmaster-dispatcher.yml")).text();
    const parsed = parseYaml(content);

    expect(parsed.name).toBe("Taskmaster Dispatcher");
    expect(parsed.jobs["code-review"]).toBeTruthy();
    expect(parsed.jobs["lint-check"]).toBeTruthy();
    expect(parsed.jobs["code-review"].secrets).toBe("inherit");
  });

  test("fails with no args", async () => {
    const { exitCode, stderr } = await runCli([]);
    expect(exitCode).toBe(1);
    expect(stderr).toContain("Usage");
  });

  test("reports validation errors for invalid fixtures", async () => {
    const invalidOutput = join(OUTPUT_DIR, "invalid-output");
    const { stderr, exitCode } = await runCli([INVALID_FIXTURES, invalidOutput]);

    expect(exitCode).toBe(1);
    expect(stderr).toContain("Validation failed");
  });
});
