import { stringify } from "yaml";
import { join } from "node:path";
import { mkdir } from "node:fs/promises";

const AUTO_GENERATED_COMMENT =
  "# Auto-generated by claude-taskmaster. Do not edit manually.\n";

/**
 * Serializes a workflow object to YAML string with the auto-generated header.
 */
export function serializeWorkflow(content: Record<string, unknown>): string {
  const yamlStr = stringify(content, {
    lineWidth: 0, // no line wrapping
    defaultStringType: "PLAIN",
    defaultKeyType: "PLAIN",
  });
  return `${AUTO_GENERATED_COMMENT}${yamlStr}`;
}

/**
 * Writes a workflow YAML file to the output directory.
 */
export async function writeWorkflowFile(
  outputDir: string,
  filename: string,
  content: Record<string, unknown>
): Promise<string> {
  await mkdir(outputDir, { recursive: true });
  const filePath = join(outputDir, filename);
  const yamlContent = serializeWorkflow(content);
  await Bun.write(filePath, yamlContent);
  return filePath;
}
